# Generated by Django 4.1.7 on 2023-03-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_subscription_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
